name: BartFi Ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  contracts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Fuel
      - run: curl --proto '=https' --tlsv1.2 -sSf https://install.fuel.network/fuelup-init.sh | sh

      - name: Build & Test
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 16.x
      - run: yarn --frozen-lockfile
      - run: yarn contracts-build
      - run: yarn contracts-test
